SELECT A.*, MNAME FROM ANIMAL A, MEMBER M WHERE A.MID=M.MID AND A.MID='jang';
SELECT A.*, MNAME FROM ANIMAL A, MEMBER M WHERE A.MID=M.MID AND A.MID LIKE '%'||'jang'||'%' AND MNAME LIKE '%'||'기'||'%' AND ANAME LIKE '%'||'동'||'%';

DROP SEQUENCE ANIMAL_SEQ;
CREATE SEQUENCE ANIMAL_SEQ;
INSERT INTO ANIMAL VALUES(ANIMAL_SEQ.NEXTVAL, 'jang2', 'noImage.jpg', '토토', '16/05/03', '개', '말티즈', '남', 0);
UPDATE ANIMAL SET APICTURE='IMAGE.JPG', ANAME='토퉁이', ABIRTH='16/01/01', ASPECIES='강아지', ASDETAIL='말티즈', AGENDER='남';
UPDATE ANIMAL SET ADELETE=1 WHERE ANUM=2;