SELECT LNAME, A.* FROM MEMBER A, MLEVEL L WHERE A.LEVELN = L.LEVELN ORDER BY MJOIN;
SELECT ROWNUM RN, AL.* FROM (SELECT LNAME, A.* FROM MEMBER A, MLEVEL L WHERE A.LEVELN = L.LEVELN ORDER BY MJOIN) AL;
SELECT * FROM (SELECT ROWNUM RN, AL.* FROM (SELECT LNAME, A.* FROM MEMBER A, MLEVEL L WHERE A.LEVELN = L.LEVELN ORDER BY MJOIN) AL) WHERE RN BETWEEN 1 AND 10;
SELECT LNAME, A.* FROM MEMBER A, MLEVEL L WHERE A.LEVELN = L.LEVELN AND MID='jang' AND A.LEVELN != 0;
SELECT LNAME, A.* FROM MEMBER A, MLEVEL L WHERE A.LEVELN = L.LEVELN AND MID LIKE '%'||''||'%' AND MNAME LIKE '%'||'이'||'%';
SELECT COUNT(*) CNT FROM MEMBER;

UPDATE MEMBER SET LEVELN=1, MPW=2222, MNAME='네이무', MBIRTH='18/01/01', MGENDER='여', MPHONE='011', MTEL='031', MADDRESS='경기', MADETAIL='이천시' WHERE MID='jang';
UPDATE MEMBER SET LEVELN=1, MPW=2222, MNAME='네이무', MBIRTH='18/01/01', MGENDER='여', MPHONE='011', MTEL='031', MADDRESS='경기', MADETAIL='이천시' WHERE MID='jang';
UPDATE MEMBER SET LEVELN=1 WHERE MID='Master';
UPDATE MEMBER SET MPW=2222, MNAME='네이무', MBIRTH='18/01/01', MGENDER='여', MPHONE='011', MTEL='031', MADDRESS='경기', MADETAIL='이천시' WHERE MID='jang';
DELETE FROM MEMBER WHERE MID='jang';

INSERT INTO MEMBER VALUES('jang', '4', '1111', '이름', sysdate, '남자', '010', '02', '서울', '도봉구', sysdate);
INSERT INTO MEMBER VALUES('Master', '1', '1111', '이름', sysdate, '남자', '010', '02', '서울', '도봉구', sysdate);

SELECT LNAME, A.* FROM MEMBER A, MLEVEL L WHERE A.LEVELN = L.LEVELN AND MID='jang' AND MPW='1111';
SELECT MID FROM MEMBER WHERE LEVELN=4;

DELETE FROM MEMBER;

COMMIT;