DROP SEQUENCE MESSAGE_SEQ;
CREATE SEQUENCE MESSAGE_SEQ;

INSERT INTO MESSAGE VALUES(MESSAGE_SEQ.NEXTVAL, 'jang', 'º¸³¿', '¿ì¿Í¾Æ¾Æ¾Ó', 'jang', sysdate, 0);
INSERT INTO MESSAGE VALUES(MESSAGE_SEQ.NEXTVAL, 'jang', 'º¸³¿', '¿ì¿Í¾Æ¾Æ¾Ó', 'jang2', sysdate, 0);
UPDATE MESSAGE SET MESREAD=0 WHERE MESNUM=1;

SELECT COUNT(*) COUNT FROM MESSAGE WHERE MID='jang';
SELECT COUNT(*) COUNT FROM MESSAGE WHERE MESFROM='jang';
SELECT * FROM MESSAGE WHERE MID='jang' AND MESREAD=0;
SELECT * FROM MESSAGE;

SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT MNAME, MES.* FROM MESSAGE MES, MEMBER M WHERE MES.MESFROM=M.MID AND m.MID='jang' ORDER BY MESDATE DESC) A) WHERE RN BETWEEN 1 AND 10;

SELECT MNAME ,MES.* FROM MESSAGE MES, MEMBER M WHERE M.MID=MES.MESFROM;
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT MNAME, MES.* FROM MESSAGE MES, MEMBER M WHERE MES.MID=M.MID ORDER BY MESDATE DESC) A) WHERE RN BETWEEN 1 AND 10 AND MESFROM='jang';

SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT MNAME, MES.* FROM MESSAGE MES, MEMBER M WHERE MES.MID=M.MID AND MESFROM='jang2' ORDER BY MESDATE DESC) A) WHERE RN BETWEEN 1 AND 10;

SELECT ROWNUM RN, A.* FROM (SELECT MNAME, MES.* FROM MESSAGE MES, MEMBER M WHERE MES.MID=M.MID ORDER BY MESDATE DESC) A;

SELECT MNAME ,MES.* FROM MESSAGE MES, MEMBER M WHERE M.MID=MES.MID AND MESNUM=1;