DROP TABLE ADDBOARD;
DROP TABLE BOARD;
DROP TABLE BOARDA;
DROP TABLE RESERVE;
DROP TABLE MESSAGE;
DROP TABLE TREATCHART;
DROP TABLE ANIMAL;
DROP TABLE MEMBER;
DROP TABLE MLEVEL;

CREATE TABLE MLEVEL(
    LEVELN NUMBER(1) PRIMARY KEY,
    LNAME VARCHAR2(30) NOT NULL);

INSERT INTO MLEVEL VALUES(0, 'OUTER');
INSERT INTO MLEVEL VALUES(1, 'MASTER');
INSERT INTO MLEVEL VALUES(2, 'SUBADMIN');
INSERT INTO MLEVEL VALUES(3, 'VIP');
INSERT INTO MLEVEL VALUES(4, 'NOMAL');

SELECT * FROM MLEVEL;

CREATE TABLE MEMBER(
    MID VARCHAR2(30) PRIMARY KEY,
    LEVELN NUMBER(1),
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(30) NOT NULL,
    MBIRTH DATE NOT NULL,
    MGENDER VARCHAR2(10) NOT NULL,
    MPHONE VARCHAR2(100) NOT NULL,
    MTEL VARCHAR2(100),
    MADDRESS VARCHAR2(200) NOT NULL,
    MADETAIL VARCHAR2(200),
    MJOIN DATE DEFAULT SYSDATE,
    FOREIGN KEY(LEVELN) REFERENCES MLEVEL(LEVELN));
    
INSERT INTO MEMBER VALUES('jang', '4', '1111', '이름', sysdate, '남자', '010', '02', '서울', '도봉구', sysdate);

CREATE TABLE ANIMAL(
    ANUM NUMBER(5) PRIMARY KEY,
    MID VARCHAR2(300),
    APICTURE VARCHAR2(100),
    ANAME VARCHAR2(30) NOT NULL,
    ABIRTH DATE,
    ASPECIES VARCHAR2(30) NOT NULL,
    ASDETAIL VARCHAR2(30),
    AGENDER VARCHAR2(10),
    ADELETE NUMBER(1) DEFAULT 0,
    FOREIGN KEY(MID) REFERENCES MEMBER(MID));
    

CREATE TABLE TREATCHART(
    TNUM NUMBER(10) PRIMARY KEY,
    ANUM NUMBER(5),
    TDATE DATE NOT NULL,
    TDETAIL VARCHAR2(1000) NOT NULL,
    TRESULT VARCHAR2(1000) NOT NULL,
    FOREIGN KEY(ANUM) REFERENCES ANIMAL(ANUM));
    
    
CREATE TABLE MESSAGE(
    MESNUM NUMBER(10) PRIMARY KEY,
    MID VARCHAR2(30) NOT NULL,
    MESTITLE VARCHAR2(100) NOT NULL,
    MESCON VARCHAR2(1000) NOT NULL,
    MESFROM VARCHAR2(30) NOT NULL,
    MESDATE DATE NOT NULL,
    MESREAD NUMBER(1) DEFAULT 0,
    FOREIGN KEY(MID) REFERENCES MEMBER(MID),
    FOREIGN KEY(MESFROM) REFERENCES MEMBER(MID));
    
    
CREATE TABLE RESERVE(
    RNUM NUMBER(3) PRIMARY KEY,
    ANUM NUMBER(5),
    RDATE DATE NOT NULL,
    RDETAIL VARCHAR2(1000) NOT NULL,
    FOREIGN KEY(ANUM) REFERENCES ANIMAL(ANUM));

    
CREATE TABLE BOARDA(
    BANUM NUMBER(1) PRIMARY KEY,
    BANAME VARCHAR(30) NOT NULL);
    
INSERT INTO BOARDA VALUES(1, 'TOP');
INSERT INTO BOARDA VALUES(2, 'HIT_Q');
INSERT INTO BOARDA VALUES(3, 'NOMAL');

CREATE TABLE BOARD(
    BNUM NUMBER(10) PRIMARY KEY,
    BANUM NUMBER(1),
    MID VARCHAR2(30),
    BNAME VARCHAR2(30) NOT NULL,
    BIP VARCHAR2(100) NOT NULL,
    BDATE DATE DEFAULT SYSDATE,
    BHIT NUMBER(5) DEFAULT 0,
    BTITLE VARCHAR2(100) NOT NULL,
    BCONTENT CLOB,
    BGROUP NUMBER(10) NOT NULL,
    BSTEP NUMBER(3) DEFAULT 0,
    BINDENT NUMBER(3) DEFAULT 0,
    BFILE VARCHAR2(100),
    FOREIGN KEY(BANUM) REFERENCES BOARDA(BANUM));
    
CREATE TABLE ADDBOARD(
    ABNUM NUMBER(10) PRIMARY KEY,
    BNUM NUMBER(10),
    MID VARCHAR2(30),
    ABCONTENT VARCHAR2(300),
    ABDATE DATE DEFAULT SYSDATE,
    FOREIGN KEY(MID) REFERENCES MEMBER(MID),
    FOREIGN KEY(BNUM) REFERENCES BOARD(BNUM));
    