DROP SEQUENCE RESERVE_SEQ;
CREATE SEQUENCE RESERVE_SEQ;

INSERT INTO RESERVE VALUES(RESERVE_SEQ.NEXTVAL, '3', '18-06-18', '광견병 예방접종');
INSERT INTO RESERVE VALUES(RESERVE_SEQ.NEXTVAL, '3', TO_DATE('18/07/18 14:00','YY/MM/DD HH24:MI'), '광견병 예방접종');
INSERT INTO RESERVE VALUES(RESERVE_SEQ.NEXTVAL, '3', TO_DATE('18/07/18 15:00','YY/MM/DD HH24:MI'), '광견병 예방접종');

SELECT ANAME, R.* FROM RESERVE R, ANIMAL A WHERE R.ANUM=A.ANUM;
SELECT TO_CHAR(RDATE,'YYMMDD HH24:MI') FROM RESERVE WHERE ANUM=3;
SELECT ANAME, R.* FROM RESERVE R, ANIMAL A WHERE R.ANUM=A.ANUM AND RNUM=2;
SELECT * FROM RESERVE WHERE RDATE = TO_DATE('180618 14:00', 'YYMMDD HH24:MI');
SELECT R.* FROM RESERVE R, ANIMAL A, MEMBER M WHERE R.ANUM=A.ANUM AND A.MID=M.MID AND M.MID='jang';

UPDATE RESERVE SET ANUM=3, RDATE='18/06/20', RDETAIL='털 미용' WHERE RNUM=2;

SELECT * FROM RESERVE WHERE RDATE = TO_DATE('18-06-20 00:00','YY-MM-DD HH24:MI');

DELETE FROM RESERVE WHERE RNUM=5;

SELECT ANAME, TO_CHAR(RDATE,'YYMMDD HH24:MI') FROM RESERVE R, ANIMAL A WHERE R.ANUM=A.ANUM AND TO_CHAR(R.RDATE, 'YYMMDD')=180618 ORDER BY RDATE;