DROP SEQUENCE TREATCHART_SEQ;
CREATE SEQUENCE TREATCHART_SEQ;

INSERT INTO TREATCHART VALUES(TREATCHART_SEQ.NEXTVAL, '3', SYSDATE, '예방접종', '접종완료');

SELECT ANAME,T.* FROM TREATCHART T, ANIMAL A WHERE T.ANUM=A.ANUM;
SELECT ANAME,T.* FROM TREATCHART T, ANIMAL A WHERE T.ANUM=A.ANUM AND ANAME LIKE '%'||''||'%' AND TO_CHAR(TDATE, 'YYMMDD')=180711;

SELECT LNAME, A.* FROM MEMBER A, MLEVEL L WHERE A.LEVELN = L.LEVELN AND MID LIKE '%'||''||'%' AND MNAME LIKE '%'||''||'%' ORDER BY A.LEVELN;